### ISSUE TITLE
Two properties of same enum type cause weird behavior when clicking Label text of second property

### ISSUE THREAD

**Issue by gakera** [Bitmapped/MvcEnumFlags#5]
# Reproduce:
Have two properties of same enum type in Controler, i.e.
```
        public MyEnumType MyEnumTypeProperty { get; set; }
        public MyEnumType MyOtherEnumTypeProperty { get; set; }
```
Where `MyEnumType `is just

```
    [Flags]
    public enum MyEnumType
    {
        // The flag for SunRoof is 0001.
        SunRoof = 0x01,
        // The flag for Spoiler is 0010.
        Spoiler = 0x02,
        // The flag for FogLights is 0100.
        FogLights = 0x04,
        // The flag for TintedWindows is 1000.
        TintedWindows = 0x08,
    }
```
And in the View: 
```
<p>Area 1.</p>

@Html.CheckBoxesForEnumFlagsFor(model => model.MyEnumTypeProperty)

<p>Another Area.</p>


@Html.CheckBoxesForEnumFlagsFor(model => model.MyOtherEnumTypeProperty)
```

## Result

When clicking the label text next to the checkboxes in the second area, the corresponding checkbox in the first area is checked, not the expected one in the second area. 

## Gif of results

![Gif](https://i.imgur.com/6It0vnr.gif)

## Sandbox project 
The relevant code is in the About page when running the solution. 
[WebApplication1.zip](https://github.com/Bitmapped/MvcEnumFlags/files/1685121/WebApplication1.zip)

**Comment by Bitmapped** [comment]
Thank you for sending the example. Right now, the labels aren't prefixed with anything to distinguish between multiple instances. This will have to be changed.

**Comment by Bitmapped** [comment]
This issue is fixed in the series of commits ending in ce04e88. I will release an updated NuGet package.

**Comment by gakera** [comment]
Ok, cool. In the hacky template I did for radiobuttons, I just created a random ID that I used for both label and radiobutton to prevent this

```
@model Enum
@foreach (var value in Enum.GetValues(Model.GetType()))
{
    var id = Guid.NewGuid().ToString();
    if (value.ToString() != "Undefined")
    {
        @Html.RadioButtonFor(m => m, value, new { @id = id })
        @Html.Label(value.ToString(), new { @for = id })
        <br />
    }

}
```

**Comment by Bitmapped** [comment]
I updated the code so it uses the name of the checkbox set as a prefix. This way, there's a predictable name for CSS and script access.
